---

- name: Install apt packages
  become: yes
  apt:
    pkg:
#    - snapd
#    - bat
    - firefox
    - htop
    - discord
#    - neovim
    - tmux
    - tree
#    - alacritty
#    - zsh
#    - appmenu-gtk3-module
    - gnome-tweaks
#    - tlp
#    - wmctrl
#    - poppler-utils
#    - libnotify-bin
#    - autojump
#    - npm
#    - redshift-gtk
    - dconf-editor

#- name: Remove apt packages
#  become: yes
#  apt:
#    name: ['falkon', 'kdeconnect', 'midori', 'kazam']
#    state: absent

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes
